using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using AIClientManager.Models;

namespace AIClientManager.Pdf
{
    public class ClientReportDocument : IDocument
    {
        private readonly Client _client;

        public ClientReportDocument(Client client)
        {
            _client = client;
        }

        public DocumentMetadata GetMetadata() => DocumentMetadata.Default;

        public void Compose(IDocumentContainer container)
        {
            container.Page(page =>
            {
                page.Margin(40);

                page.Header().Row(row =>
                {
                    row.RelativeColumn()
                        .Text("AI Client Report")
                        .FontSize(22)
                        .Bold();

                    row.ConstantColumn(120)
                        .AlignRight()
                        .Text(DateTime.Now.ToString("yyyy-MM-dd"));
                });

                page.Content().Column(col =>
                {
                    col.Spacing(15);

                    col.Item().Text($"Client: {_client.Name}")
                        .FontSize(16)
                        .Bold();

                    col.Item().Text($"Company: {_client.Company}");
                    col.Item().Text($"Email: {_client.Email}");

                    col.Item().LineHorizontal(1);

                    col.Item().Row(r =>
                    {
                        r.RelativeColumn().Text($"Priority: {_client.Priority}");
                        r.RelativeColumn().Text($"Score: {_client.Score}");
                    });

                    col.Item().Text("AI Summary:")
                        .Bold();

                    col.Item().Text(_client.Summary);

                    col.Item().Text("Keywords:")
                        .Bold();

                    col.Item().Text(_client.Keywords);
                });

                page.Footer()
                    .AlignCenter()
                    .Text("Generated by AI Client Manager")
                    .FontSize(10);
            });
        }
    }
}
